<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

// library wajib seeder
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Hash; 

class BengkelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    // contoh bentuk benarnya 'https://maps.google.com/?q=-3.278461,114.574509',
    // -3.278461,114.574509
    public function run(): void
    {
        $bengkelData = [
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.278461,114.574509',
                'id_user'=>7,
                'nama_bengkel' => 'Bengkel Jaya Motor',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. Pangeran Antasari No.12',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.3190496,114.5757471',
                'nama_bengkel' => 'Bengkel Motor Sejahtera',
                'id_user'=>8,
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. Ahmad Yani No.45',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'jam_operasional' => '09:00-18:00',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.354733,114.599776',
                'nama_bengkel' => 'Bengkel Mandiri',
                'id_user'=>9,
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Gatot Subroto No.7',
                'jam_buka' => '07:30',
                'jam_tutup' => '16:30',
                'jam_operasional' => '07:30-16:30',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.312758,114.616216',
                'nama_bengkel' => 'Bengkel Bersama',
                'id_user'=>10,
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Lambung Mangkurat No.88',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.322135,114.571172',
                'nama_bengkel' => 'Bengkel Prima',
                'id_user'=>11,
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. A. Yani Km.5',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'jam_operasional' => '08:30-17:30',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- 25 Data Lanjutan (id_user 12 - 36) ---

            // Kecamatan Utara (5 Data)
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.293157, 114.589744',
                'id_user'=>12,
                'nama_bengkel' => 'Bengkel Respati I',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. Kayu Tangi No. 1A',
                'jam_buka' => '08:00',
                'jam_tutup' => '18:00',
                'jam_operasional' => '08:00-18:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.287675,114.575072',
                'id_user'=>13,
                'nama_bengkel' => 'Bengkel Otomotor II',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. Sungai Andai No. 2B',
                'jam_buka' => '09:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '09:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.295522,114.611062',
                'id_user'=>14,
                'nama_bengkel' => 'Bengkel Mandiri III',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. Alalak Selatan No. 3C',
                'jam_buka' => '08:30',
                'jam_tutup' => '16:30',
                'jam_operasional' => '08:30-16:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.270800,114.567819',
                'id_user'=>15,
                'nama_bengkel' => 'Bengkel Motor IV',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. Sultan Adam No. 4D',
                'jam_buka' => '07:00',
                'jam_tutup' => '15:00',
                'jam_operasional' => '07:00-15:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.301172,114.584587',
                'id_user'=>16,
                'nama_bengkel' => 'Bengkel Motor Jaya V',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. H. Hasan Basri No. 5E',
                'jam_buka' => '10:00',
                'jam_tutup' => '19:00',
                'jam_operasional' => '10:00-19:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Kecamatan Tengah (5 Data)
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.316261,114.574947',
                'id_user'=>17,
                'nama_bengkel' => 'Auto Service Utama I',
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. Sudirman No. 6A',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.312834,114.588680',
                'id_user'=>18,
                'nama_bengkel' => 'Cepat Ganti Oli II',
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. Pangeran Samudra No. 7B',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'jam_operasional' => '08:00-16:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.318746,114.603658',
                'id_user'=>19,
                'nama_bengkel' => 'Pusat Ban Motor III',
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. Merdeka No. 8C',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'jam_operasional' => '09:00-18:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.325815,114.601984',
                'id_user'=>20,
                'nama_bengkel' => 'Bengkel Motor Jaya IV',
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. Veteran No. 9D',
                'jam_buka' => '07:30',
                'jam_tutup' => '15:30',
                'jam_operasional' => '07:30-15:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.326415,114.588466',
                'id_user'=>21,
                'nama_bengkel' => 'Budi Motor V',
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. S Parman No. 10E',
                'jam_buka' => '10:00',
                'jam_tutup' => '20:00',
                'jam_operasional' => '10:00-20:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Kecamatan Barat (5 Data)
            [
                'link_gmaps' => 'https://maps.google.com/?q-3.295487,114.569973',
                'id_user'=>22,
                'nama_bengkel' => 'Bengkel Cepat & Tepat I',
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. Belitung Darat No. 11A',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.319671,114.572173',
                'id_user'=>23,
                'nama_bengkel' => 'Bengkel Service II',
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. Sutoyo S No. 12B',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'jam_operasional' => '09:00-18:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.323273,114.570224',
                'id_user'=>24,
                'nama_bengkel' => 'Prima Auto III',
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. Teluk Tiram No. 13C',
                'jam_buka' => '07:00',
                'jam_tutup' => '16:00',
                'jam_operasional' => '07:00-16:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.311529,114.579282',
                'id_user'=>25,
                'nama_bengkel' => 'Bengkel Barokah IV',
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. Brigjen Hasan Basri No. 14D',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'jam_operasional' => '08:30-17:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.301441,114.570694',
                'id_user'=>26,
                'nama_bengkel' => 'Motor Cepat V',
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. Cemara Raya No. 15E',
                'jam_buka' => '10:00',
                'jam_tutup' => '19:00',
                'jam_operasional' => '10:00-19:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Kecamatan Selatan (5 Data)
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.347786,114.567842',
                'id_user'=>27,
                'nama_bengkel' => 'Bengkel Selatan I',
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Pramuka No. 16A',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.365417,114.620097',
                'id_user'=>28,
                'nama_bengkel' => 'Jaya Abadi II',
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Lingkar Selatan No. 17B',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'jam_operasional' => '09:00-18:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.352572,114.625802',
                'id_user'=>29,
                'nama_bengkel' => 'Motor Expert III',
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Gubernur Soebardjo No. 18C',
                'jam_buka' => '07:30',
                'jam_tutup' => '16:30',
                'jam_operasional' => '07:30-16:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.344667,114.611345',
                'id_user'=>30,
                'nama_bengkel' => 'Bengkel AC Motor IV',
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Gerilya No. 19D',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.337178,114.599097',
                'id_user'=>31,
                'nama_bengkel' => 'Ganti Oli Cepat V',
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Trans Kalimantan No. 20E',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'jam_operasional' => '08:30-17:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],

            // Kecamatan Timur (5 Data)
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.335850,114.615570',
                'id_user'=>32,
                'nama_bengkel' => 'Bengkel Sejati I',
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Kuripan No. 21A',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.320575,114.612033',
                'id_user'=>33,
                'nama_bengkel' => 'Pusat Motor II',
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Gatot Subroto No. 22B',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'jam_operasional' => '09:00-18:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.320215,114.624808',
                'id_user'=>34,
                'nama_bengkel' => 'Bengkel Tiga Rasa III',
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Kelayan B No. 23C',
                'jam_buka' => '07:30',
                'jam_tutup' => '16:30',
                'jam_operasional' => '07:30-16:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.346226,114.631232',
                'id_user'=>35,
                'nama_bengkel' => 'Bengkel Tunas IV',
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Banjar Indah Permai No. 24D',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jam_operasional' => '08:00-17:00',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'link_gmaps' => 'https://maps.google.com/?q=-3.331743,114.624086',
                'id_user'=>36,
                'nama_bengkel' => 'Sinar Motor V',
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Veteran No. 25E',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'jam_operasional' => '08:30-17:30',
                'status' => 'aktif',
                'created_at' => now(), 'updated_at' => now(),
            ],
        ];

        DB::table('bengkel')->insert($bengkelData);
    }
}