<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class BengkelSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'id_user' => 6,
                'nama_bengkel' => 'Bengkel Diesel FAJAR KHB',
                'kecamatan' => 'Astambul',
                'alamat_lengkap' => 'Jl. Keramat RT.01 RW.01 No. 09 Desa Keramat',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.295487,
                'longitude' => 114.569973,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 7,
                'nama_bengkel' => 'SYAILENDRA DIESEL',
                'kecamatan' => 'Tamban',
                'alamat_lengkap' => 'Jl. Trans Kalimantan RT.01 RW.02 No. 06 Desa',
                'jam_buka' => '09:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.010732,
                'longitude' => 114.564563,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 8,
                'nama_bengkel' => 'Tuwuh Mandiri',
                'kecamatan' => 'Bumi Makmur',
                'alamat_lengkap' => 'Jl. Barito Kuala No. 02 Lt 3 Desa Manunggal',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.085224,
                'longitude' => 114.562010,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 9,
                'nama_bengkel' => 'Abadi Jaya Technic',
                'kecamatan' => 'Tabunganen',
                'alamat_lengkap' => 'Jl. Raya Pesayangan',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -2.987653,
                'longitude' => 114.553927,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 10,
                'nama_bengkel' => 'Bengkel 3 R',
                'kecamatan' => 'Mekarsari',
                'alamat_lengkap' => 'JL. Mekar Vit RT.01',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:00',
                'latitude' => -3.302942,
                'longitude' => 114.599236,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 11,
                'nama_bengkel' => 'Bengkel Gurgal',
                'kecamatan' => 'Bati-Bati',
                'alamat_lengkap' => 'Jl. Gaharu Gang Jamuju',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.351573,
                'longitude' => 114.672940,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 12,
                'nama_bengkel' => 'Bengkel Damai',
                'kecamatan' => 'Jingah Habang Hilir',
                'alamat_lengkap' => 'Jl. Karang Intan',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.366642,
                'longitude' => 114.664428,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 13,
                'nama_bengkel' => 'Bengkel Tembikar',
                'kecamatan' => 'Loktabat Selatan',
                'alamat_lengkap' => 'Jl. Tegal Paring',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.459612,
                'longitude' => 114.809830,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 14,
                'nama_bengkel' => 'Wiracana Bengkel',
                'kecamatan' => 'Aranio',
                'alamat_lengkap' => 'Jl. Kiram No. 05 RT.02 RW.03 Desa Kiram',
                'jam_buka' => '10:00',
                'jam_tutup' => '19:00',
                'latitude' => -3.468900,
                'longitude' => 114.858568,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 15,
                'nama_bengkel' => 'Bengkel Singgah Mati',
                'kecamatan' => 'Halong',
                'alamat_lengkap' => 'Jl. Kuala Kapuas RT.03 RW.01',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -2.805224,
                'longitude' => 114.619245,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 16,
                'nama_bengkel' => 'Auto Service Mandiri',
                'kecamatan' => 'Pelaihari',
                'alamat_lengkap' => 'Jl. A. Yani KM 100',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.805224,
                'longitude' => 114.850000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 17,
                'nama_bengkel' => 'Motor Sejahtera',
                'kecamatan' => 'Banjarmasin Utara',
                'alamat_lengkap' => 'Jl. Sultan Adam No. 55',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'latitude' => -3.298000,
                'longitude' => 114.591000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 18,
                'nama_bengkel' => 'Teknik Jaya Abadi',
                'kecamatan' => 'Banjarmasin Tengah',
                'alamat_lengkap' => 'Jl. Pangeran Samudra No. 12',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'latitude' => -3.321855, 
                'longitude' => 114.593339,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 19,
                'nama_bengkel' => 'Motor Prima Jaya',
                'kecamatan' => 'Banjarmasin Barat',
                'alamat_lengkap' => 'Jl. Sutoyo S No. 10',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.320400, 
                'longitude' => 114.580000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 20,
                'nama_bengkel' => 'Bengkel Cepat Tanggap',
                'kecamatan' => 'Banjarmasin Selatan',
                'alamat_lengkap' => 'Jl. Pramuka No. 1A',
                'jam_buka' => '07:30',
                'jam_tutup' => '16:30',
                'latitude' => -3.337000, 
                'longitude' => 114.610000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 21,
                'nama_bengkel' => 'Bengkel Umum Timur',
                'kecamatan' => 'Banjarmasin Timur',
                'alamat_lengkap' => 'Jl. Kuripan No. 22',
                'jam_buka' => '09:00',
                'jam_tutup' => '19:00',
                'latitude' => -3.315000, 
                'longitude' => 114.605000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 22,
                'nama_bengkel' => 'Multi Service Diesel',
                'kecamatan' => 'Gambuth',
                'alamat_lengkap' => 'Jl. A. Yani KM 17',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.325000,
                'longitude' => 114.700000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 23,
                'nama_bengkel' => 'Bintang Motor',
                'kecamatan' => 'Martapura',
                'alamat_lengkap' => 'Jl. Sekumpul Raya No. 10',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.400000,
                'longitude' => 114.850000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 24,
                'nama_bengkel' => 'Motor Plus Service',
                'kecamatan' => 'Landasan Ulin',
                'alamat_lengkap' => 'Jl. Angkasa Pura No. 5',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'latitude' => -3.440000,
                'longitude' => 114.770000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 25,
                'nama_bengkel' => 'Bengkel Barokah',
                'kecamatan' => 'Sungai Tabuk',
                'alamat_lengkap' => 'Jl. Martapura Lama KM 12',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'latitude' => -3.330000,
                'longitude' => 114.650000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 26,
                'nama_bengkel' => 'Cepat Ganti Oli',
                'kecamatan' => 'Aluh Aluh',
                'alamat_lengkap' => 'Jl. Aluh-Aluh No. 8',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.450000,
                'longitude' => 114.570000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 27,
                'nama_bengkel' => 'Teknik Handal',
                'kecamatan' => 'Bakumpai',
                'alamat_lengkap' => 'Jl. Basirih Selatan No. 20',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'latitude' => -3.100000,
                'longitude' => 114.600000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 28,
                'nama_bengkel' => 'Jasa Motor Terbaik',
                'kecamatan' => 'Belawang',
                'alamat_lengkap' => 'Jl. Raya Belawang KM 5',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.200000,
                'longitude' => 114.400000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 29,
                'nama_bengkel' => 'Bengkel Sejati',
                'kecamatan' => 'Jaro',
                'alamat_lengkap' => 'Jl. Raya Jaro No. 1',
                'jam_buka' => '07:30',
                'jam_tutup' => '16:30',
                'latitude' => -2.300000,
                'longitude' => 115.400000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 30,
                'nama_bengkel' => 'Diesel Expert',
                'kecamatan' => 'Kelumpang Hilir',
                'alamat_lengkap' => 'Jl. Nasional 1 No. 33',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.600000,
                'longitude' => 115.600000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 31,
                'nama_bengkel' => 'Motor Service Plus',
                'kecamatan' => 'Paminggir',
                'alamat_lengkap' => 'Jl. Desa Paminggir No. 10',
                'jam_buka' => '08:30',
                'jam_tutup' => '17:30',
                'latitude' => -3.000000,
                'longitude' => 114.900000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 32,
                'nama_bengkel' => 'Bengkel Serba Ada',
                'kecamatan' => 'Binuang',
                'alamat_lengkap' => 'Jl. Raya Binuang KM 1',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.330000,
                'longitude' => 115.000000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 33,
                'nama_bengkel' => 'Prima Teknik Motor',
                'kecamatan' => 'Karang Intan',
                'alamat_lengkap' => 'Jl. Karang Intan No. 5',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'latitude' => -3.400000,
                'longitude' => 114.700000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 34,
                'nama_bengkel' => 'Bengkel Mitra Usaha',
                'kecamatan' => 'Cempaka',
                'alamat_lengkap' => 'Jl. Cempaka No. 7',
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'latitude' => -3.450000,
                'longitude' => 114.800000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_user' => 35,
                'nama_bengkel' => 'Motor Jaya Bersama',
                'kecamatan' => 'Kertak Hanyar',
                'alamat_lengkap' => 'Jl. A. Yani KM 7',
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'latitude' => -3.350000,
                'longitude' => 114.610000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'id_user' => 36,
                'nama_bengkel' => 'Bengkel Utama Diesel',
                'kecamatan' => 'Berangas',
                'alamat_lengkap' => 'Jl. Raya Berangas KM 3',
                'jam_buka' => '09:00',
                'jam_tutup' => '18:00',
                'latitude' => -3.200000,
                'longitude' => 114.500000,
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        foreach ($data as &$row) {
            $row['link_gmaps'] = "https://maps.google.com/?q={$row['latitude']},{$row['longitude']}";
            $row['jam_operasional'] = $row['jam_buka'] . '-' . $row['jam_tutup'];
        }
        unset($row); 

        DB::table('bengkel')->insert($data);
    }
}